package example; 

/**
 * Consumes "events" generated by a "publisher" class that this listens to.
 */
public class Listener1 implements Listener {
  public void handleEvent(Object event) {
    System.out.println("event received : " + String.valueOf(event));
  }
}
