package example;

/**
 * An interface that classes implement if they wish to subscribe to the events generated by a Publisher instance.
 */
public interface Listener
{
  void handleEvent(Object someEventInfo);
}
